/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DaemonRouteImport } from './routes/daemon'
import { Route as IndexRouteImport } from './routes/index'

const DaemonRoute = DaemonRouteImport.update({
  id: '/daemon',
  path: '/daemon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daemon': typeof DaemonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daemon': typeof DaemonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daemon': typeof DaemonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daemon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daemon'
  id: '__root__' | '/' | '/daemon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaemonRoute: typeof DaemonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/daemon': {
      id: '/daemon'
      path: '/daemon'
      fullPath: '/daemon'
      preLoaderRoute: typeof DaemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaemonRoute: DaemonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
